services:
  frontend:
    image: csaba44/miniplex-frontend:latest
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
  backend:
    image: csaba44/miniplex-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
